name: Build Circle Analyzer

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Create executable
        run: |
          pyinstaller --onefile --name circle-analyzer main.py

      - name: Prepare release files
        run: |
          mkdir release
          copy dist\circle-analyzer.exe release\
          copy start.bat release\
          copy requirements.txt release\
          copy README.md release\
          copy LICENSE release\

      - name: Create ZIP archive
        run: |
          cd release
          7z a ..\circle-analyzer.zip *

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: circle-analyzer.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
